from google.cloud import bigquery

open_meteo_hourly: list[bigquery.SchemaField] = [
    bigquery.SchemaField("location_id", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("location_name", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("latitude", "FLOAT", mode="REQUIRED"),
    bigquery.SchemaField("longitude", "FLOAT", mode="REQUIRED"),
    bigquery.SchemaField("observed_at", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("temperature_2m", "FLOAT"),
    bigquery.SchemaField("relative_humidity_2m", "FLOAT"),
    bigquery.SchemaField("dew_point_2m", "FLOAT"),
    bigquery.SchemaField("apparent_temperature", "FLOAT"),
    bigquery.SchemaField("pressure_msl", "FLOAT"),
    bigquery.SchemaField("surface_pressure", "FLOAT"),
    bigquery.SchemaField("cloud_cover", "FLOAT"),
    bigquery.SchemaField("cloud_cover_low", "FLOAT"),
    bigquery.SchemaField("cloud_cover_mid", "FLOAT"),
    bigquery.SchemaField("cloud_cover_high", "FLOAT"),
    bigquery.SchemaField("wind_speed_10m", "FLOAT"),
    bigquery.SchemaField("wind_direction_10m", "FLOAT"),
    bigquery.SchemaField("wind_gusts_10m", "FLOAT"),
    bigquery.SchemaField("precipitation", "FLOAT"),
    bigquery.SchemaField("rain", "FLOAT"),
    bigquery.SchemaField("showers", "FLOAT"),
    bigquery.SchemaField("snowfall", "FLOAT"),
    bigquery.SchemaField("weather_code", "INTEGER"),
    bigquery.SchemaField("snow_depth", "FLOAT"),
    bigquery.SchemaField("freezing_level_height", "FLOAT"),
    bigquery.SchemaField("visibility", "FLOAT"),
    bigquery.SchemaField("is_day", "BOOLEAN"),
    bigquery.SchemaField("ingested_at", "TIMESTAMP", mode="REQUIRED"),
]
